# Generated by Django 5.1.6 on 2025-03-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_logic', '0002_needy_reviews_needyimage_reviewsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsimage',
            old_name='review',
            new_name='reviews',
        ),
    ]
