# Generated by Django 5.1.6 on 2025-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_logic', '0003_rename_review_reviewsimage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
