# Generated by Django 5.1.6 on 2025-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_logic', '0005_telegramuser_delete_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reviewsimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
