# Generated by Django 5.1.6 on 2025-03-28 10:17

import telegram_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_userphone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/', validators=[telegram_bot.models.validate_audio_file])),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
            },
        ),
    ]
